categories = {
    "All things": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",

    "3D Printing": "Machinery \\ 3D Printer Parts & Accessories \\ 3D Printer Accessories",
    "3D Printer Accessories ": "Machinery \\ 3D Printer Parts & Accessories \\ 3D Printer Accessories",
    "3D Printer Extruders": "Machinery \\ 3D Printer Parts & Accessories \\ 3D Printer Extruders",
    "3D Printer Parts": "Machinery \\ 3D Printer Parts & Accessories \\ 3D Printer Accessories",
    "3D Printers": "Machinery \\ 3D Printer Parts & Accessories \\ 3D Printer Accessories",
    "3D Printing Tests": " Machinery \\ 3D Printer Parts & Accessories \\ 3D Printer Accessories",

    "Art": "Gifts & Crafts \\ Arts & Crafts Supplies \\ Art",
    "2D Art": "Gifts & Crafts \\ Arts & Crafts Supplies \\ Art",
    "Art Tools": "Gifts & Crafts \\ Arts & Crafts Supplies \\ Art",
    "Coins & Badges": " Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Interactive Art": "Gifts & Crafts \\ Arts & Crafts Supplies \\ Art",
    "Math Art": "Gifts & Crafts \\ Arts & Crafts Supplies \\ Art",
    "Scans & Replicas": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Sculptures": "Toys & Hobbies \\ Action Figure \\ Other Action Figure",
    "Signs & Logos": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",

    "Fashion": "Fashion Accessories \\ Other Fashion Accessories \\ Other Fashion Accessories",
    "Accessories": "Fashion Accessories \\ Other Fashion Accessories \\ Other Fashion Accessories",
    "Bracelets": "Timepieces, Jewelry, Eyewear \\ Jewelry \\ Bracelets & Bangles",
    "Costume": "Fashion Accessories \\ Other Fashion Accessories \\ Other Fashion Accessories",
    "Earrings": "Timepieces, Jewelry, Eyewear \\ Jewelry \\ Earrings",
    "Glasses": "Timepieces, Jewelry, Eyewear \\ Eyewear \\ Sunglasses",
    "Jewelry": "Timepieces, Jewelry, Eyewear \\ Other Jewelry \\ Other",
    "Keychains": "Timepieces, Jewelry, Eyewear \\ Other Jewelry \\ Other",
    "Rings": "Timepieces, Jewelry, Eyewear \\ Jewelry \\ Rings",

    "Gadgets": "Consumer Electronics \\ Other Consumer Electronics \\ Other",
    "Audio": "Consumer Electronics \\ Other Consumer Electronics \\ Other",
    "Camera": "Consumer Electronics \\ Photographic, Filming & Video Equipment \\ Cameras",
    "Computer": "Consumer Electronics \\ Other Consumer Electronics \\ Other",
    "Mobile Phone": "Consumer Electronics \\ Mobile Phone & Accessories \\ Other Mobile Phone Accessories",
    "Tablet": "Consumer Electronics \\ Other Consumer Electronics \\ Other",
    "Video Games": "Consumer Electronics \\ Other Consumer Electronics \\ Other",

    "Automotive": "Vehicles & Accessories \\ Automotive Parts & Accessories \\ Other Auto Parts",
    "DIY": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Electronics": "Consumer Electronics \\ Other Consumer Electronics \\ Other",
    "Music": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "R/C Vehicles": "Consumer Electronics \\ Other Consumer Electronics \\ Other",
    "Robotics": "Consumer Electronics \\ Other Consumer Electronics \\ Other",
    "Sport & Outdoors": "Sports & Entertainment \\ Sports Equipment & Accessories \\ Other",

    "Household": "Home & Garden \\ Home Decor \\ Other Home Decor",
    "Bathroom": "Home & Garden \\ Bathroom Products \\ Other Bath & Toilet Supplies",
    "Containers": "Home & Garden \\ Home Decor \\ Other Home Decor",
    "Decor": "Home & Garden \\ Home Decor \\ Other Home Decor",
    "Household Supplies": "Home & Garden \\ Home Decor \\ Other Home Decor",
    "Kitchen & Dining": "Home & Garden \\ Kitchen & Tabletop \\ Table Decoration & Accessories",
    "Office Organization": " Home & Garden \\ Home Decor \\ Other Home Decor",
    "Outdoor & Garden": "Home & Garden \\ Garden Supplies \\ Other Garden Supplies",
    "Pets": "Home & Garden \\ Pet Products \\ Other Pet Products",

    "Learning": "Office & School Supplies \\ Education Supplies \\ Other Educational Supplies",
    "Biology": "Office & School Supplies \\ Education Supplies \\ Other Educational Supplies",
    "Engineering": "Office & School Supplies \\ Education Supplies \\ Other Educational Supplies",
    "Math": "Office & School Supplies \\ Education Supplies \\ Other Educational Supplies",
    "Physics & Astronomy": "Office & School Supplies \\ Education Supplies \\ Other Educational Supplies",

    "Models": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Animals": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Buildings & Structures": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Creatures": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Food & Drink": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Model Furniture": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Model Robots": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "People": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Props": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",
    "Vehicles": "Gifts & Crafts \\ Other Gifts & Crafts \\ Other Gifts & Crafts",

    "Tools": "Tools & Hardware \\ Other Tool \\ Other Tools",
    "Hand Tools ": "Tools & Hardware \\ Other Tool \\ Other Tools",
    "Machine Tools ": "Tools & Hardware \\ Other Tool \\ Other Tools",
    "Tool Holders & boxes": "Tools & Hardware \\ Other Tool \\ Other Tools",

    "Toys & Games": "Toys & Hobbies \\ Toys & Games \\ Other",
    "Chess": "Toys & Hobbies \\ Toys & Games \\ Other",
    "Construction Toys": "Toys & Hobbies \\ Toys & Games \\ Other",
    "Dice": "Toys & Hobbies \\ Toys & Games \\ Other",
    "Games": "Toys & Hobbies \\ Toys & Games \\ Other",
    "Mechanical Toys": "Toys & Hobbies \\ Toys & Games \\ Other",
    "Playsets": "Toys & Hobbies \\ Toys & Games \\ Other",
    "Puzzles": "Toys & Hobbies \\ Toys & Games \\ Other",
    "Toy & Game Accessories": "Toys & Hobbies \\ Toys & Games \\ Other",
    "Other": "Toys & Hobbies \\ Toys & Games \\ Other",
}